export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const AUTH_REFRESH_FAIL = 'AUTH_REFRESH_FAIL';
export const AUTH_REFRESH_SUCCESS = 'AUTH_REFRESH_SUCCESS';
