# Generated by Django 4.2 on 2023-05-18 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentCRM",
            fields=[
                ("st_id", models.AutoField(primary_key=True, serialize=False)),
                ("st_name", models.CharField(max_length=255)),
                ("st_surname", models.CharField(max_length=255)),
                ("st_patronymic", models.CharField(max_length=255)),
                ("st_birthdate", models.DateField()),
                ("st_gender", models.CharField(max_length=255)),
                ("st_description", models.TextField()),
                ("st_createdAt", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "student_crm",
            },
        ),
        migrations.CreateModel(
            name="CourseCRM",
            fields=[
                ("cr_id", models.AutoField(primary_key=True, serialize=False)),
                ("cr_name", models.CharField(max_length=255)),
                ("cr_startdate", models.DateField()),
                ("cr_enddate", models.DateField()),
                ("cr_description", models.TextField()),
                ("cr_nowst", models.IntegerField()),
                ("cr_maxst", models.IntegerField()),
                ("cr_status", models.CharField(max_length=255)),
                (
                    "st_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.studentcrm",
                    ),
                ),
            ],
            options={
                "db_table": "course_crm",
            },
        ),
        migrations.CreateModel(
            name="ContactsCRM",
            fields=[
                ("ct_id", models.AutoField(primary_key=True, serialize=False)),
                ("ct_name", models.CharField(max_length=255)),
                ("ct_person", models.CharField(max_length=255)),
                ("ct_number", models.IntegerField(max_length=12)),
                ("ct_email", models.EmailField(max_length=254)),
                (
                    "st_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.studentcrm",
                    ),
                ),
            ],
            options={
                "db_table": "contacts_crm",
            },
        ),
    ]
