# Generated by Django 4.2 on 2023-05-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactscrm",
            name="ct_number",
            field=models.IntegerField(),
        ),
    ]
