# Generated by Django 4.2 on 2023-05-18 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_alter_contactscrm_ct_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactscrm",
            name="ct_email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="coursecrm",
            name="cr_description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="coursecrm",
            name="st_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.studentcrm",
            ),
        ),
        migrations.AlterField(
            model_name="studentcrm",
            name="st_description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="studentcrm",
            name="st_patronymic",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
