# Generated by Django 4.2 on 2023-05-06 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_coursematerial_enrollment_notification_payment_plan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergroup',
            old_name='name',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='parent_phone_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_group',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='UserGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.usergroup', verbose_name='ID привязанной роли'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Дата рождения ученика'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО ученика'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=1, null=True, verbose_name='Пол ученика'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='parent_contact_1',
            field=models.CharField(max_length=255, null=True, verbose_name='Контакт родителя 1 (номер и имя и кем он приходится ребенку)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='parent_contact_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контакт родителя 2 (номер и имя и кем он приходится ребенку)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='student_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к ученику'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='parent_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Почта родителя (для создания аккаунта)'),
        ),
    ]
