# Generated by Django 4.2 on 2023-05-18 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_alter_contactscrm_ct_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursecrm",
            name="cr_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coursecrm",
            name="st_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.studentcrm",
            ),
        ),
    ]
