# Generated by Django 4.2 on 2023-05-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_name_usergroup_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergroup',
            old_name='user',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='parent_contact_1',
            field=models.CharField(max_length=255, null=True, verbose_name='Контакт родителя 1'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='parent_contact_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контакт родителя 2'),
        ),
    ]
