# Generated by Django 4.2 on 2023-05-19 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_remove_contactscrm_st_id_remove_coursecrm_st_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursecrm",
            name="st_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.studentcrm",
            ),
        ),
    ]
