# Generated by Django 4.2 on 2023-05-19 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_coursecrm_st_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactscrm",
            name="st_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.studentcrm",
            ),
            preserve_default=False,
        ),
    ]
