# Generated by Django 4.2 on 2023-05-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_contactscrm_st_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactscrm",
            name="st_id",
        ),
        migrations.RemoveField(
            model_name="coursecrm",
            name="st_id",
        ),
        migrations.AddField(
            model_name="contactscrm",
            name="students",
            field=models.ManyToManyField(to="base.studentcrm"),
        ),
        migrations.AddField(
            model_name="coursecrm",
            name="students",
            field=models.ManyToManyField(blank=True, to="base.studentcrm"),
        ),
    ]
