# Generated by Django 4.2 on 2023-05-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_remove_contactscrm_st_id_remove_coursecrm_st_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactscrm",
            name="students",
            field=models.ManyToManyField(related_name="contacts", to="base.studentcrm"),
        ),
        migrations.AlterField(
            model_name="coursecrm",
            name="students",
            field=models.ManyToManyField(
                blank=True, related_name="courses", to="base.studentcrm"
            ),
        ),
    ]
