# Generated by Django 4.2 on 2023-05-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0009_alter_contactscrm_students_alter_coursecrm_students"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursecrm",
            name="cr_nowst",
            field=models.IntegerField(default=0),
        ),
    ]
